app = "wg-keen-routes"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

# Критически важные настройки
[deploy]
  release_command = "python -c 'import os; os.system(\"sleep 10\")'"

[checks]
  [checks.health]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"